server:
  port: 8080

spring:
  application:
    name: cooperative-voting-api
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperative_voting_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true

logging:
  level:
    root: INFO
